name: Terraform Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: "us-east-1" # Adjust this to your desired AWS region

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
